#############################
# deploy_nexus_sonatype_iac #
#############################

app:
  name: nexus-sonatype
  version: 3.62.0-01 
  os_user: nexus
  folder: /opt/sonatype
  port: 8081
  user_home: /home/nexus
   
bashrc_env:
  - "export BASE_URL=http://{{ ansible_hostname }}:8081"
  - "export NEXUS_HOME=/opt/sonatype/nexus"
  - "export NEXUS_CASC_CONFIG=/opt/nexus.yml"   
  - "export NEXUS_UI_PORT=8081"   
  - "export PLUGIN_VERSION={{ app.version }}"   
  - "export SONATYPE_DIR=/opt/sonatype"   
  - "export SONATYPE_WORK=/opt/sonatype/sonatype-work"  
  - "export HOME=/opt/sonatype/nexus"   
  - "export PWD=/opt/sonatype"  
  
git_plugin: https://github.com/AdaptiveConsulting/nexus-casc-plugin.git
url_package: https://download.sonatype.com/nexus/3/nexus-{{ app.version }}-unix.tar.gz

firewall_list:
  - "{{ app.port }}/tcp"
  - 8070/tcp

tmp_folder: /tmp  