---

- name: Bootstrap Nexus Sonatype IAC
  hosts: nexus
  gather_facts: true
  any_errors_fatal: true
  become: true   
  vars:
    nexus_ver: 3.62.0-01
  roles: 
    - { role: common, update: true, download_bin: true, adduser: true } 
    - { role: common, allowport: true }   
    - { role: nexus, setup_bashrc: true } 
    - { role: nexus, setup_folder: true }   
    - { role: nexus, setup_startup: true }   
    - { role: nexus, iac: true }   
  tags: 
    - deploy_centos8
           