---

- name: Bootstrap Nexus Sonatype IAC
  hosts: nexus
  any_errors_fatal: true
  become: true   
  vars:
    nexus_ver: 3.62.0-01   
    packages_list:
      - epel-release 
      - wget
      - java-1.8.0-openjdk.x86_64 
      - git
    plugin_list:
      - java-1.8.0-openjdk.x86_64 
      - git 
      - maven     
  roles: 
    - { role: rv-common, update: true, download_bin: true, adduser: true } 
    - { role: rv-common, allowport: true }   
    - { role: nexus, setup_bashrc: true } 
    - { role: nexus, setup_folder: true }   
    - { role: nexus, setup_startup: true }   
    - { role: nexus, iac: true }   
  tags: 
    - deploy_centos8
           