---

- name: ping
  hosts: nexus
  gather_facts: false
  # become: true
  vars:
    testy: "test"

  tasks: 
    - shell: echo {{ ansible_hostname }} > /tmp/host
    #   register: reg
    # - debug: var=reg
    # - ping: 
    # - shell: ls /root
    #   become: true
    # - shell: echo "{{testy}}"
    #   register: reg
    # - debug: var=reg
    