---

- name: enable script
  shell: |
         grep nexus.scripts.allowCreation=true /opt/sonatype/sonatype-work/nexus3/etc/nexus.properties || echo "nexus.scripts.allowCreation=true" >> /opt/sonatype/sonatype-work/nexus3/etc/nexus.properties

- name: Copy nexus.yml
  template:
    src: nexus.j2
    dest: "/opt/nexus.yml"
    mode: '0755' 
    owner: nexus

- name: change attribute and ownership
  include_tasks: chown.yaml


start nexus
