---

- name: Save init password to bashrc
  shell: |
         echo "export NEXUS_PASSWD=`cat /opt/sonatype/sonatype-work/nexus3/admin.password`" >> /home/nexus/.bashrc

- name: Enable IAC
  shell: |
         grep nexus.scripts.allowCreation=true /opt/sonatype/sonatype-work/nexus3/etc/nexus.properties || echo "nexus.scripts.allowCreation=true" >> /opt/sonatype/sonatype-work/nexus3/etc/nexus.properties

- name: Copy nexus.yml
  template:
    src: nexus.j2
    dest: "/opt/nexus.yml"
    mode: '0755' 
    owner: nexus

- name: git clone 
  shell: |
         git clone --depth 1 --branch v"{{nexus_ver}}".0 https://github.com/AdaptiveConsulting/nexus-casc-plugin.git
  args:
    chdir: /tmp                   

- name: Create plugin package
  shell: |
         ./mvnw package
  args:
    chdir: /tmp/nexus-casc-plugin                       

- name: Copy the plugin 
  shell: |
         cp ./target/nexus-casc-plugin-"{{nexus_ver}}"-bundle.kar /opt/sonatype/nexus/deploy/
  args:
    chdir: /tmp/nexus-casc-plugin                           

- name: Change attribute and ownership
  include_tasks: chown.yml

- name: Start nexus service again
  ansible.builtin.systemd_service:
    name: nexus
    state: started

- name: Wait for nexus to start listening on port 8081
  ansible.builtin.wait_for:
    port: 8081
    host: 0.0.0.0

# - name: Stop nexus service again
#   ansible.builtin.systemd_service:
#     name: nexus
#     state: stopped    

# - name: Cleanup 
#   shell: | 
#          rm -f /opt/nexus*.tar.gz*
#          rm -f /opt/nexus.yml      

# - name: End message
#   shell: |
#          echo "********************************************************************************"
#          echo "* Please do the first login to the $BASE_URL, change the password and save it! *"  
#          echo "* To finish the Nexus Sonatype Setup.                                          *"
#          echo "********************************************************************************"
#   become_user: nexus        

# - shell: echo "Restart nexus service"
#   notify: "Restart nexus service"       
