---

- set_fact: 
   get_content: true
   folder_path: "{{ app.folder }}/sonatype-work/nexus3/admin.password"

- name: Get the temp password
  include_role:
    name: rv-common
    tasks_from: get_content

- set_fact: tmp_pwd="{{mounts['content']|b64decode}}"
  no_log: true

- set_fact:
    update_file: true
    folder_path: "{{app.user_home}}/.bashrc"
    search_string: "export NEXUS_PASSWD="
    new_string: 'export NEXUS_PASSWD={{tmp_pwd}}'  
  no_log: true

- name: Update the bashrc with NEXUS_PASSWD
  include_role:
    name: rv-common
    tasks_from: update_file

- set_fact:
    update_file: true
    folder_path: "{{ app.folder }}/sonatype-work/nexus3/etc/nexus.properties"
    search_string: "nexus.scripts.allowCreation=true"
    new_string: 'nexus.scripts.allowCreation=true'  

- name: Enable IAC
  include_role:
    name: rv-common
    tasks_from: update_file         

- name: Copy nexus.yml
  template:
    src: nexus.yml.j2
    dest: "/opt/nexus.yml"
    mode: '0755' 
    owner: nexus
    group: nexus
                
- set_fact:
    change_permission: true
    os_user: "{{ app.os_user }}"
    file_mode: 0755
    recursive: yes
    file_list:
      - "{{ app.folder }}/nexus"
      - "{{ app.folder }}/sonatype-work"
    
- name: Change the permission recursively of app folders
  include_role:
    name: rv-common
    tasks_from: change_permission

- name: Start using the script
  include_tasks: start_stop.yml

- set_fact:
    remove_files: true
    remove_content: true
    folder_path: "{{ app.folder }}/sonatype-work/nexus3/etc/nexus.properties"
    search_string: "nexus.scripts.allowCreation=true"
    file_list:
      - "{{tmp_folder}}/nexus-{{app.version}}-unix.tar.gz"
      - /opt/nexus.yml   
      - /opt/nexus.sh

- name: Cleanup files
  include_role:
    name: rv-common
    tasks_from: remove_files

- name: Cleanup content
  include_role:
    name: rv-common
    tasks_from: remove_content


- name: End message
  shell: |
         echo "********************************************************************************"
         echo "* Please do the first login to the $BASE_URL, change the password and save it! *"  
         echo "* To finish the Nexus Sonatype Setup.                                          *"
         echo "********************************************************************************"
  become_user: nexus        

- name: Finally start nexus with daemon service
  shell: echo "Restart nexus daemon"
  notify: "Restart nexus service"       
