---

- name: Save init password to bashrc
  shell: |
         echo "export NEXUS_PASSWD=`cat /opt/sonatype/sonatype-work/nexus3/admin.password`" >> /home/nexus/.bashrc

- name: Enable IAC
  shell: |
         grep nexus.scripts.allowCreation=true /opt/sonatype/sonatype-work/nexus3/etc/nexus.properties || echo "nexus.scripts.allowCreation=true" >> /opt/sonatype/sonatype-work/nexus3/etc/nexus.properties

- name: Copy nexus.yml
  template:
    src: nexus.yml.j2
    dest: "/opt/nexus.yml"
    mode: '0755' 
    owner: nexus
    group: nexus
