---

- name: git clone 
  shell: |
         git clone --depth 1 --branch v"{{nexus_ver}}".0 https://github.com/AdaptiveConsulting/nexus-casc-plugin.git
  args:
    chdir: /tmp                   

- name: Create plugin package
  shell: |
         ./mvnw package
  args:
    chdir: /tmp/nexus-casc-plugin 

- name: Copy the plugin to local
  ansible.builtin.fetch:
    src: /tmp/nexus-casc-plugin/target/nexus-casc-plugin-{{nexus_ver}}-bundle.kar
    dest: /tmp     