---

- name: Get the plugin name
  shell: echo {{ groups['plugin'] }} 
  register: reg

- set_fact: 
    vm_name: "{{reg.stdout | replace('[','') | replace(']','')}}"

- name: copy the plugin to nexus
  ansible.builtin.copy:
    src: "/tmp/{{ vm_name }}/tmp/nexus-casc-plugin/target/nexus-casc-plugin-3.62.0-01-bundle.kar"
    dest: /opt/sonatype/nexus/deploy/  

- name: Change attribute and ownership
  include_tasks: chown.yml

- name: Start using the script
  include_tasks: start_stop.yml

- name: Cleanup 
  shell: | 
         rm -f /opt/nexus*.tar.gz*
         rm -f /opt/nexus.yml    
         sed -i 's/nexus.scripts.allowCreation=true//' /opt/sonatype/sonatype-work/nexus3/etc/nexus.properties  

- name: End message
  shell: |
         echo "********************************************************************************"
         echo "* Please do the first login to the $BASE_URL, change the password and save it! *"  
         echo "* To finish the Nexus Sonatype Setup.                                          *"
         echo "********************************************************************************"
  become_user: nexus        

- name: Finally start nexus with daemon service
  shell: echo "Restart nexus daemon"
  notify: "Restart nexus service"        