---

- include_tasks: setup_bashrc.yml
  when: setup_bashrc|default(False)==True  
          
- include_tasks: setup_folder.yml
  when: setup_folder|default(False)==True  

- include_tasks: setup_startup.yml
  when: setup_startup|default(False)==True  

- include_tasks: iac1.yml
  when: iac1|default(False)==True  

- include_tasks: iac2.yml
  when: iac2|default(False)==True  

- include_tasks: iac3.yml
  when: iac3|default(False)==True  
