---

- include_tasks: setup_bashrc.yml
  when: setup_bashrc|default(False)==True  
          
- include_tasks: setup_folder.yml
  when: setup_folder|default(False)==True  

- include_tasks: setup_startup.yml
  when: setup_startup|default(False)==True  

- include_tasks: iac.yml
  when: iac|default(False)==True  
