---

- set_fact: 
   fail_if_exist: true
   unarchive: true

- name: call task from another role
  include_role:
    name: rv-common
    tasks_from: fail_if_exist

- name: call task from another role
  include_role:
    name: rv-common
    tasks_from: unarchive

- name: setup nexus folder
  shell: mv {{ app.folder }}/nexus-"{{ app.version }}" "{{ app.folder }}"/nexus
 
- name: Create nexus script -without this IAC will not be possible
  template:
    src: nexus.sh.j2
    dest: "/opt/nexus.sh"
    mode: '0755' 
    owner: nexus
    group: nexus

- set_fact:
    update_file: true
    folder_path: "{{ app.folder }}/nexus/bin/nexus.rc"
    search_string: "run_as_user"
    new_string: 'run_as_user="nexus"'  

- name: call task from another role
  include_role:
    name: rv-common
    tasks_from: update_file
          
- name: change attribute and ownership
  include_tasks: chown.yml