---

- name: setup nexus folder
  shell: |
         tar xvf nexus-"{{ nexus_ver }}"-unix.tar.gz
         mkdir sonatype
         mv nexus-"{{ nexus_ver }}" nexus
         mv nexus/ sonatype/
         mv sonatype-work/ sonatype/
         chown -R nexus:nexus /opt/sonatype/nexus
         chown -R nexus:nexus /opt/sonatype/sonatype-work
         chmod -R 755 /opt/sonatype/nexus
         chmod -R 755 /opt/sonatype/sonatype-work
  args:
    chdir: /opt

- name: Check /opt/nexus.sh exists
  stat:
    path: /opt/nexus.sh
  register: stat_result

- name: create nexus script
  shell: | 
         tee -a nexus.sh << END    
         #!/bin/bash
         cd /opt/sonatype/nexus
         exec ./bin/nexus run    
         END
         chmod 755 nexus.sh
         chown nexus:nexus nexus.sh
  args:
    chdir: /opt
  when: not stat_result.stat.exists  
