---

- name: Create systemd nexus
  template:
    src: nexus.service.j2
    dest: "/etc/systemd/system/nexus.service"
    mode: '0755' 
    owner: root
  
- name: First start of nexus so sa to generate the init password
  service:
    name: nexus
    state: started
  notify: "Wait for nexus to start listening on port 8081"

- name: First stop of nexus
  service:
    name: nexus
    state: stopped
