---

- name: setup nexus folder
  shell: |
         tar xvf nexus-"{{ nexus_ver }}"-unix.tar.gz
         mkdir sonatype
         mv nexus-"{{ nexus_ver }}" nexus
         mv nexus/ sonatype/
         mv sonatype-work/ sonatype/
  args:
    chdir: /opt
 
- name: Create nexus script -without this IAC will not be possible
  template:
    src: nexus.sh.j2
    dest: "/opt/nexus.sh"
    mode: '0755' 
    owner: nexus
    group: nexus

- name: make run_as_user as nexus
  shell: |
         echo 'run_as_user="nexus"' > /opt/sonatype/nexus/bin/nexus.rc  

- name: change attribute and ownership
  include_tasks: chown.yml