---

- name: Create systemd nexus
  template:
    src: nexus.service.j2
    dest: "/etc/systemd/system/nexus.service"
    mode: '0755' 
    owner: root

- name: Daemon reload
  shell: systemctl daemon-reload    
  
- name: First start of nexus
  ansible.builtin.systemd_service:
    name: nexus
    state: started

- name: Wait for nexus to start listening on port 8081
  ansible.builtin.wait_for:
    port: 8081
    host: 0.0.0.0

- name: First stop of nexus
  ansible.builtin.systemd_service:
    name: nexus
    state: stopped
