---

- include_tasks: update.yml
  when: update|default(False)==True  
          
- include_tasks: download_bin.yml
  when: download_bin|default(False)==True

- include_tasks: adduser.yml
  when: adduser|default(False)==True

- include_tasks: allowport.yml
  when: allowport|default(False)==True

- include_tasks: cleanup.yml
  when: cleanup|default(False)==True
